Feature local storage
BlesslinJerishR/Microfolio pull request #12
Opened 2023-04-13 12:24 UTC by BlesslinJerishR

- Add LocalStorage functionality for the form

2023-04-13 13:28 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has commits only from one group member in a pari-programming project. Every member must have at least one commit in the PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-13 14:29 UTC, Ibizugbe requested changes
Hi @BlesslinJerishR 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/231790729-2f816a4e-30e1-4920-a669-8856b71f5dd8.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] The [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters is set correctly project repository.The [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters are correctly setup and they are passing👍.
- [x] Github flow practice has been used👍. 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 14:29 UTC, Ibizugbe commented on script.js
> +// li.classList.add('badge');
Kindly take away every commented block of code as they make your code base look a bit messy and less professional😉

2023-04-13 14:29 UTC, Ibizugbe commented on script.js
> +});
Nice work so far👍. Your contact form information is not retained when you reload the page🥲 and this is a requirement in this milestone. kindly make the necessary change👍

<img width="721" alt="image" src="https://user-images.githubusercontent.com/64643995/231788911-e5d3b5b5-fd7e-41a0-9089-92a10648a90a.png">

2023-04-13 14:29 UTC, Ibizugbe commented on script.js
> +  localStorage.setItem('email', email.value);
It is required that You must create a single JavaScript object with all the data from the entire form and save it in local storage. kindly implement this feature to retain data from your local storage on your input fields on page load 👍

![image](https://user-images.githubusercontent.com/64643995/231789899-e0d63ac1-22f2-40a5-9359-b7e171aeef38.png)

kindly ensure the features in the[ requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/10_localstorage.md) are implemented👍

2023-04-14 11:32 UTC, amejid reviewed
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where linter checks are not running. Please resolve the merge conflict so linters can run properly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-14 13:06 UTC, Strangeal approved these changes
Hi @BlesslinJerishR, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 06:38 UTC, merged